server:
  port: 8080

spring:
    datasource: 
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        username: root
        password: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect  
    mvc:
        view:
            suffix: .jsp
            prefix: /WEB-INF/views/ 
    thymeleaf:
        cache: false
        enable-spring-el-compiler: false 
        
    redis:
        host: 127.0.0.1
        port: 6379
        pool:
            max-active: 8
            max-wait: 1
            max-idle: 8
            min-idle: 0  
        timeout: 0             

mybatis:
  typeAliasesPackage: com.example.model
  mapperLocations: classpath:mapping/*.xml 
  
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
       enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    